### ISSUE TITLE
need a gitignore

### ISSUE THREAD

**Issue by omarcostahamido** [MauroSilvaPinto/The-Algorithm-of-Epilepsy#1]
some pesky `.ds_store` files laying around.
I propose to clean that and set a gitignore

**Comment by omarcostahamido** [comment]
@MauroSilvaPinto ok I see that you beat me to deleting the files. I usually use the `assignees` list (top right on issue page here) to let the other ppl know when I am working on an issue. but no worries 😄  thank you

**Comment by MauroSilvaPinto** [comment]
sorry! first time actually using the "issues" option here. didn't realize that part until now ahah
