### ISSUE TITLE
Consider space management

### ISSUE THREAD

**Issue by omarcostahamido** [MauroSilvaPinto/The-Algorithm-of-Epilepsy#2]
The repo is already 300+MB, mostly due to the videos.
It is bad to be populating the history with these files because, well, every update on these will stay there in the history.
I may suggest hosting as yt link or something, or maybe explore the github large file storage system LFS - which I've been meaning to explore for a while and haven't found an opportunity to! Just my 2 cents. You decide.

**Comment by MauroSilvaPinto** [comment]
Done! I posted the video links on the README files, directly from my drive.
