### ISSUE TITLE
Clarifying GoL structures

### ISSUE THREAD

**Issue by omarcostahamido** [MauroSilvaPinto/The-Algorithm-of-Epilepsy#5]
@MauroSilvaPinto 
RE https://github.com/MauroSilvaPinto/The-Algorithm-of-Epilepsy/blob/main/Game_of_life/README.md
Could you add some simple explanation of what those structures mean?
>Many structures are available, including spaceships, oscillators, still forms, and some methuselahs.

**Comment by MauroSilvaPinto** [comment]
Done! Added some helpful links
